### ISSUE TITLE
Gerar layout da carteira digital

### ISSUE THREAD

**Issue by lucaspiquera** [enckecorp/EnckeWallet#1]
Gerar layout pensando em fluidez sem perder sobriedade de um sistema administrativo (para versão desk-navegador).

**Comment by lucaspiquera** [comment]
Link documentação referência:
- https://getbootstrap.com/docs/5.3/examples/

**Comment by lucaspiquera** [comment]
Referência externa:
https://ibitelecom.com.br/blog/aplicativos-para-controle-financeiro/

**Comment by myrawcs** [comment]
![image](https://github.com/enckecorp/EnckeWallet/assets/97454825/31c991a5-7874-4c43-9066-e5f1b59c732d)
Definição inicial de paleta de cores, fase experimental

**Comment by myrawcs** [comment]
28/11 - definição da paleta de cores (experimental)
- início do desenvolvimeto Ux, com os elementos do bootstrap

**Comment by myrawcs** [comment]
@lucaspiquera Quais módulos/funcionalidades você vê como obrigatórias? Tem algo que você terceiro que você imagina que tenha?
/

**Comment by lucaspiquera** [comment]
> @lucaspiquera Quais módulos/funcionalidades você vê como obrigatórias? Tem algo que você terceiro que você imagina que tenha? /

Pensei em uma estrutura de módulos parecida com o padrão que temos em aplicativos de banco. Onde temos saídas entradas, um extrato elaborado e informativo e gráficos (muitos gráficos). 

No quesito "elementos de terceiros" vamos futuramente precisar de integração com os bancos mais famosos do Brasil para importação de extratos e facilitar o preenchimento dos dados de movimentos do cliente, mas de início os que serão realmente indispensáveis serão os de inserção de movimentos, extrato e dashboard da página inicial.

**Comment by myrawcs** [comment]
> > @lucaspiquera Quais módulos/funcionalidades você vê como obrigatórias? Tem algo que você terceiro que você imagina que tenha? /
> 
> @myrawcs Pensei em uma estrutura de módulos parecida com o padrão que temos em aplicativos de banco. Onde temos saídas entradas, um extrato elaborado e informativo e gráficos (muitos gráficos).
> 
> No quesito "elementos de terceiros" vamos futuramente precisar de integração com os bancos mais famosos do Brasil para importação de extratos e facilitar o preenchimento dos dados de movimentos do cliente, mas de início os que serão realmente indispensáveis serão os de inserção de movimentos, extrato e dashboard da página inicial.

Perfeito, muito obrigada pela prontidão!😊

**Comment by myrawcs** [comment]
Entrega do layout da carteira digital finalizado até no máximo 3/12

**Comment by myrawcs** [comment]
30/11/2023 - Layout site aprentação
![Home](https://github.com/enckecorp/EnckeWallet/assets/97454825/bbe5304d-b613-4a98-aeff-956a40cf2b4f)
![About](https://github.com/enckecorp/EnckeWallet/assets/97454825/b166689e-6905-4930-ae33-866be8c86e24)
![Download Now](https://github.com/enckecorp/EnckeWallet/assets/97454825/253f49a9-306f-4bce-b108-114470f56b35)
![Features](https://github.com/enckecorp/EnckeWallet/assets/97454825/da2e2f99-cc7c-4e7c-8118-b51d066771b1)
![Philosophy](https://github.com/enckecorp/EnckeWallet/assets/97454825/832396d4-b791-40ef-a9f6-9a15e7fdbb19)
![Feedback](https://github.com/enckecorp/EnckeWallet/assets/97454825/e275a9fb-5960-4535-b332-def1fa1b52d1)
![Contact](https://github.com/enckecorp/EnckeWallet/assets/97454825/6c81b27b-4717-4e01-8c04-8ccb20e500e9)
